-- MySQL Script generated by MySQL Workbench
-- Thu Nov 26 19:03:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api` DEFAULT CHARACTER SET utf8 ;
USE `api` ;

-- -----------------------------------------------------
-- Table `api`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api`.`Chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api`.`Chats` (
  `idChats` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idChats`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api`.`Mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api`.`Mensajes` (
  `idMensajes` INT NOT NULL AUTO_INCREMENT,
  `Texto` VARCHAR(45) NOT NULL,
  `Fecha` DATE NULL,
  `Chats_idChats` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idMensajes`, `Chats_idChats`, `Usuarios_idUsuarios`),
  INDEX `fk_Mensajes_Chats1_idx` (`Chats_idChats` ASC) VISIBLE,
  INDEX `fk_Mensajes_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Mensajes_Chats1`
    FOREIGN KEY (`Chats_idChats`)
    REFERENCES `api`.`Chats` (`idChats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensajes_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `api`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api`.`Chats_has_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api`.`Chats_has_Usuarios` (
  `Chats_idChats` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`Chats_idChats`, `Usuarios_idUsuarios`),
  INDEX `fk_Chats_has_Usuarios_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Chats_has_Usuarios_Chats_idx` (`Chats_idChats` ASC) VISIBLE,
  CONSTRAINT `fk_Chats_has_Usuarios_Chats`
    FOREIGN KEY (`Chats_idChats`)
    REFERENCES `api`.`Chats` (`idChats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chats_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `api`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
